deploy-docker.yml





# Checkout site
# Push to web servers
# Execute build script in site



#- name: Installing Puppet
#  apt: name=puppet state=present update_cache=yes
#- name: Enable Puppet
#  shell: puppet agent --enable
#- name: Installing Puppetmaster
#  apt: name=puppetmaster state=present update_cache=yes
#  when: instance_role == "master"
#- name: Bootstrapping uppet
#  shell: 'rm -rf /etc/puppet'
#- copy: src=files/puppet.tar.gz dest=/etc
#- shell: 'tar -xvzf puppet.tar.gz'
#  args:
#    chdir: /etc
#- shell: 'bash /etc/puppet/bootstrap.sh {{ instance_role }}'

#- name: Clone puppet repo
#  git: >
#    repo="{{ puppet_repo_url }}"
#    dest="files/puppet"
#    version="{{ puppet_repo_branch }}"
#- name: Archive puppet repo
#  shell: 'tar -zcvf puppet.tar.gz puppet'
#  args:
#    chdir: files/
.
