
- name: Ensure droplet exists
  digital_ocean: >
    state=present
    command=droplet
    client_id="{{ do_client_id }}"
    api_key="{{ do_api_key }}"
    ssh_key_ids="{{ do_default_ssh_key }}"
    name={{ item.name }}
    size_id={{ item.size|default(do_default_size) }}
    region_id={{ item.region|default(do_default_region) }}
    image_id={{ item.image|default(do_default_image) }}
    wait_timeout=600
    unique_name=true
  register: new_droplets
  with_items: droplets

- debug: >
    msg="IP is {{ item.droplet.ip_address }}"
  with_items: new_droplets.results

- name: Ensure new Droplets IP is not in known hosts
  shell: 'ssh-keygen -f "$HOME/.ssh/known_hosts" -R {{ item.droplet.ip_address }}'
  when: item.changed
  with_items: new_droplets.results

- name: Adding new Droplets to hosts
  #debug: "{{ item.['item']['instance_role'] }}"
  add_host: name={{ item.droplet.ip_address }} groups=new_droplets instance_role={{ item.item.instance_role }}
  when: item.changed
  with_items: new_droplets.results
