- name: Create new Droplet
  digital_ocean: >
    state=present
    command=droplet
    name={{ do_droplet_name }}
    client_id="{{ do_client_id }}"
    api_key="{{ do_api_key }}"
    size_id=66
    region_id=2
    image_id=3101918
    ssh_key_ids="{{ do_ssh_key_id }}"
    wait_timeout=600
  register: new_droplet
- debug: >
    msg="ID is {{ new_droplet.droplet.id }}"
- debug: >
    msg="IP is {{ new_droplet.droplet.ip_address }}"
- name: Ensure new Droplets IP is not in known hosts
  shell: 'ssh-keygen -f "$HOME/.ssh/known_hosts" -R {{ new_droplet.droplet.ip_address }}'
- name: Adding new Droplet to hosts
  add_host: name={{ new_droplet.droplet.ip_address }} groups=newdroplet
