- name: Ensure droplet exists
  digital_ocean: >
    state=present
    command=droplet
    client_id="{{ do_client_id }}"
    api_key="{{ do_api_key }}"
    ssh_key_ids="{{ do_default_ssh_key }}"
    name={{ item.name }}
    size_id={{ item.size|default(do_default_size) }}
    region_id={{ item.region|default(do_default_region) }}
    image_id={{ item.image|default(do_default_image) }}
    wait_timeout=600
    unique_name=true
  register: new_droplet
  with_items: droplets

- debug: >  tasks:
    msg="ID is {{ new_droplet.droplet.id }}"
- debug: >
    msg="IP is {{ new_droplet.droplet.ip_address }}"

- name: Ensure new Droplets IP is not in known hosts
  shell: 'ssh-keygen -f "$HOME/.ssh/known_hosts" -R {{ new_droplet.droplet.ip_address }}'

- name: Adding new Droplet to hosts
  add_host: name={{ new_droplet.droplet.ip_address }} groups=droplets

#- debug: msg="IP is {{ item.droplet.ip_address }}"
#  with_items: droplet.results    - include: tasks/create_droplet.yml droplets={{droplets}}
